name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc jq

      - id: ensure_license
        name: Ensure MIT License exists (and mark if created)
        run: |
          if [ ! -f LICENSE ]; then
            YEAR=$(date +%Y)
            printf '%s\n' "MIT License" "" "Copyright (c) $YEAR ${{ github.actor }}" > LICENSE
            echo "created=true" >> $GITHUB_OUTPUT
          else
            echo "created=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate index.html if missing
        run: |
          set -e
          GENERATED=0
          if [ -f index.html ]; then
            echo "Keeping existing index.html (not regenerating)."
          elif [ -f README.md ]; then
            echo "Generating index.html from README.md with syntax highlighting..."
            pandoc README.md -f markdown -t html -s               --highlight-style=tango               -o index.html               --metadata title="${{ github.event.repository.name }}"
            GENERATED=1
          else
            echo "No index.html or README.md found; writing minimal page."
            printf '%s\n' '<!doctype html><html><head><meta charset="utf-8"><title>Site</title></head><body>'                            '<h1>Site</h1>'                            '<p>No README.md found. Add one and push to regenerate this page.</p>'                            '</body></html>' > index.html
            GENERATED=1
          fi

          if [ $GENERATED -eq 1 ]; then
            echo "Injecting CSS for centering and white background..."
            sed -i '/<head>/a <style>body{font-family:Arial,Helvetica,sans-serif;margin:0;background:#fff;color:#000;display:flex;flex-direction:column;align-items:center;}</style>' index.html
            sed -i '/<body>/a <main style="max-width:1000px;width:90%;margin:20px auto;text-align:center;">' index.html
            echo "</main>" >> index.html
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

